redis:
    image: redis:7.4-alpine
    container_name: ldds-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-lddsredispass}
      - REDIS_CLUSTER_MODE=${REDIS_CLUSTER_MODE:-false}
      - REDIS_AUTHENTICATION=${REDIS_AUTHENTICATION:-false}
    command:
      - sh
      - -c
      - |
        if [ "$REDIS_CLUSTER_MODE" = "true" ]; then
          echo "🚀 Starting Redis in CLUSTER mode..."
          if [ "$REDIS_AUTHENTICATION" = "true" ]; then
            redis-server \
              --requirepass "$REDIS_PASSWORD" \
              --user "ldds on >$REDIS_PASSWORD ~* +@all" \
              --cluster-enabled yes \
              --cluster-config-file nodes.conf \
              --cluster-node-timeout 5000 \
              --appendonly yes \
              --save 20 1 \
              --loglevel warning
          else
            redis-server \
              --cluster-enabled yes \
              --cluster-config-file nodes.conf \
              --cluster-node-timeout 5000 \
              --appendonly yes \
              --save 20 1 \
              --loglevel warning
          fi
        else
          echo "🔹 Starting Redis in STANDALONE mode..."
          if [ "$REDIS_AUTHENTICATION" = "false" ]; then
            redis-server \
              --save 20 1 \
              --appendonly yes \
              --loglevel warning
            exit 0
          else
            redis-server \
              --requirepass "$REDIS_PASSWORD" \
              --user "ldds on >$REDIS_PASSWORD ~* +@all" \
              --save 20 1 \
              --appendonly yes \
              --loglevel warning
          fi
        fi
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-lddsredispass}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
