code-server:
  image: codercom/code-server:latest
  container_name: ldds-code-server
  restart: unless-stopped
  environment:
    - PASSWORD=${CODE_SERVER_PASSWORD:-code_password}
    - BIND_ADDR=0.0.0.0
    - PORT=${CODE_SERVER_PORT:-8080}
  ports:
    - "8443:${CODE_SERVER_PORT:-8080}"
  volumes:
    - code_server_data:/home/coder/project
