n8n:
  image: n8nio/n8n:latest
  container_name: ldds-n8n
  restart: unless-stopped
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_PORT=${POSTGRES_PORT:-5432}
    - DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-n8n}
    - DB_POSTGRESDB_USER=${POSTGRES_USER:-n8n}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD:-n8n_password}
    - N8N_PORT=${N8N_PORT:-5678}
    - N8N_BASIC_AUTH_ACTIVE=false
    - GENERIC_TIMEZONE=Europe/Madrid
  ports:
    - "${N8N_PORT:-5678}:5678"
  volumes:
    - n8n_data:/home/node/.n8n
  depends_on:
    - postgres
