version: "3.8"
services:
  hello-world:
    image: nginx:alpine
    container_name: sample_hello_nginx
    restart: unless-stopped
    ports:
      - "18080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
